### ISSUE TITLE
Airzone avec plusieurs ne fonctionne pas

### ISSUE THREAD

**Issue by Mat2Vence** [Elwinmage/AirZone#1]
Bonsoir,
J'ai deux système Airzone : 

- un système desservant uniquement une pièce
- un système desservant 3 chambres.

Je n'ai aucun soucis avec les deux système pour accéder via 'API local. Ils ont la même version logicielle.
Pas de problème pour l'intégration du système ne desservant qu'une pièce.

Par conte pour le système multi-zone, je me retrouve avec les erreurs suivantes, et donc les devices ne sont pas créer sous domoticz.

`2023-07-23 22:57:27.200 Error: CLIM Etage: Call to function 'onHeartbeat' failed, exception details:

2023-07-23 22:57:27.201 Error: CLIM Etage: Traceback (most recent call last):

2023-07-23 22:57:27.201 Error: CLIM Etage: File "/home/pi/domoticz/plugins/AirZone/plugin.py", line 317, in onHeartbeat

2023-07-23 22:57:27.201 Error: CLIM Etage: _plugin.onHeartbeat()

2023-07-23 22:57:27.201 Error: CLIM Etage: File "/home/pi/domoticz/plugins/AirZone/plugin.py", line 187, in onHeartbeat

2023-07-23 22:57:27.201 Error: CLIM Etage: self.updateStatus()

2023-07-23 22:57:27.201 Error: CLIM Etage: File "/home/pi/domoticz/plugins/AirZone/plugin.py", line 199, in updateStatus

2023-07-23 22:57:27.201 Error: CLIM Etage: mode = self._modes[zone['mode']]

2023-07-23 22:57:27.201 Error: CLIM Etage: KeyError: 2`

Pour info : 

`Version: 2023.2

Build Hash: 19efd039c

Compile Date: 2023-07-21 16:23:44

dzVents Version: 3.1.8

Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]`

**Comment by Elwinmage** [comment]
Can't repro
