### ISSUE TITLE
Erreurs après redémarrage

### ISSUE THREAD

**Issue by Mat2Vence** [Elwinmage/AirZone#2]
Je rajoute un nouveau ticket par rapport à des erreurs qui apparaissent sur mon module Airzone pourtant fonctionnel après un redémarrage.
J'ai fait un redémarrage de Domoticz suite un a reboot du Rpi, et j'ai à présent des messqge d'erreur sur mon système qui n'en produisant pas jusqu'alors  : 
`2023-07-23 23:07:55.260 Error: CLIM Salon: Call to function 'onHeartbeat' failed, exception details:

2023-07-23 23:07:55.260 Error: CLIM Salon: Traceback (most recent call last):

2023-07-23 23:07:55.260 Error: CLIM Salon: File "/home/pi/domoticz/plugins/AirZone/plugin.py", line 317, in onHeartbeat

2023-07-23 23:07:55.260 Error: CLIM Salon: _plugin.onHeartbeat()

2023-07-23 23:07:55.260 Error: CLIM Salon: File "/home/pi/domoticz/plugins/AirZone/plugin.py", line 187, in onHeartbeat

2023-07-23 23:07:55.261 Error: CLIM Salon: self.updateStatus()

2023-07-23 23:07:55.261 Error: CLIM Salon: File "/home/pi/domoticz/plugins/AirZone/plugin.py", line 199, in updateStatus

2023-07-23 23:07:55.261 Error: CLIM Salon: mode = self._modes[zone['mode']]

2023-07-23 23:07:55.261 Error: CLIM Salon: KeyError: 2`

Le système semble néanmoins fonctionnel puisqu'un modification de consigne de température a bien été transmise au Airzone.

**Comment by Elwinmage** [comment]
Pouvez-vous installer la dernière version et  activer le mode debug en bas de la page du matériel. A première vu je dirais que le json renvoyé ne contient pas le mode de la zone...

**Comment by Elwinmage** [comment]
Can't repro
